# Dockerfile.node
FROM python:3.11-slim

WORKDIR /app

# Copy seluruh proyek ke dalam container
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Default environment variables
ENV HOST=0.0.0.0
ENV PORT=8000

EXPOSE 8000 9000 9100

# Command default (bisa diubah lewat docker-compose)
CMD ["python", "-m", "src.main"]
